#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : locket
Version  : 0.2.0
Release  : 6
URL      : https://files.pythonhosted.org/packages/d0/22/3c0f97614e0be8386542facb3a7dcfc2584f7b83608c02333bced641281c/locket-0.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/d0/22/3c0f97614e0be8386542facb3a7dcfc2584f7b83608c02333bced641281c/locket-0.2.0.tar.gz
Summary  : File-based locks for Python for Linux and Windows
Group    : Development/Tools
License  : BSD-2-Clause-FreeBSD
Requires: locket-python3
Requires: locket-license
Requires: locket-python
BuildRequires : buildreq-distutils3

%description
=========
        
        Locket implements a lock that can be used by multiple processes provided they use the same path.

%package license
Summary: license components for the locket package.
Group: Default

%description license
license components for the locket package.


%package python
Summary: python components for the locket package.
Group: Default
Requires: locket-python3

%description python
python components for the locket package.


%package python3
Summary: python3 components for the locket package.
Group: Default
Requires: python3-core

%description python3
python3 components for the locket package.


%prep
%setup -q -n locket-0.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537215470
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/locket
cp LICENSE %{buildroot}/usr/share/doc/locket/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/locket/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
